# Generated by Django 3.2.9 on 2022-02-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20220204_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('billet', "peut actribuer un billet d'avion"), ('validation', 'peut faire une validation'), ('numero', 'peut attribuer le numero'), ('forfait', 'peut changer le forfait'))},
        ),
        migrations.RemoveField(
            model_name='stepprocess',
            name='type_steps1',
        ),
        migrations.AlterField(
            model_name='stepprocess',
            name='type_steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.typesteps'),
        ),
    ]
