# Generated by Django 3.2.9 on 2022-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_rights_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('billets', "peut actribuer un billet d'avion"), ('validation', 'peut faire une validation'), ('numero', 'peut attribuer le numero'), ('forfait', 'peut changer le forfait'), ('paiement', 'peut faire un paiement'), ('justification', 'peut valider des justificatifs'))},
        ),
        migrations.AlterField(
            model_name='processus',
            name='type_process',
            field=models.CharField(choices=[('NO', 'Normal'), ('PO', 'Pôle'), ('PR', 'Projet')], max_length=5),
        ),
    ]
