# Generated by Django 3.2.9 on 2022-03-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20220328_1614'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.service'),
        ),
    ]
