# Generated by Django 3.2.9 on 2022-03-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20220328_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.service1'),
        ),
    ]
