# Generated by Django 3.2.9 on 2022-03-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_employe_id_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.service'),
        ),
       
    ]
