# Generated by Django 3.2.9 on 2022-03-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_auto_20220328_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.service'),
        ),
    ]
