# Generated by Django 3.2.9 on 2022-03-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_alter_employe_id_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.service1'),
        ),
    ]
