# Generated by Django 3.2.9 on 2022-03-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_auto_20220328_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service1',
            new_name='Service2',
        ),
    ]
