# Generated by Django 3.2.9 on 2022-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20220328_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='login_employe',
            field=models.CharField(max_length=255),
        ),
    ]
