# Generated by Django 3.2.9 on 2022-03-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0021_alter_employe_login_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='id_entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quickstart.entite'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quickstart.typeprojet'),
        ),
        migrations.AlterField(
            model_name='stepprocess',
            name='cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='stepprocess',
            name='id_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quickstart.processus'),
        ),
        migrations.AlterField(
            model_name='stepprocess',
            name='type_steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quickstart.typesteps'),
        ),
    ]
