# Generated by Django 3.2.9 on 2022-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_auto_20220330_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='user.png', upload_to='photo'),
        ),
    ]
