# Generated by Django 3.2.9 on 2022-04-11 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0023_employe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id_bank', models.AutoField(primary_key=True, serialize=False)),
                ('sigle', models.CharField(max_length=20)),
                ('nom_bank', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('type_paiement', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='photo/user.png', upload_to='photo'),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id_cheque', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('id_bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id_actions', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_action', models.CharField(max_length=255)),
                ('id_mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.mission')),
                ('id_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
