# Generated by Django 3.2.9 on 2022-04-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0024_auto_20220411_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_cheque_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.cheque'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_tresorier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_tresorier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
