# Generated by Django 3.2.9 on 2022-04-12 14:45

from django.db import migrations,models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_auto_20220412_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cheque',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_envoye_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='quickstart.envoye'),
            preserve_default=False,
        ),
    ]
