# Generated by Django 3.2.9 on 2022-04-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0028_rename_chaque_paiement_cheque'),
        ('quickstart', '0029_remove_paiement_type_paiement'),
    ]

    operations = [
    ]
