# Generated by Django 3.2.9 on 2022-04-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0030_merge_20220412_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='type_paiement',
        ),
    ]
