# Generated by Django 3.2.9 on 2022-04-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0031_remove_paiement_type_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='cheque',
        ),
    ]
