# Generated by Django 3.2.9 on 2022-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0032_remove_paiement_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cheque',
            field=models.BooleanField(default=False),
        ),
    ]
