# Generated by Django 3.2.9 on 2022-04-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0033_paiement_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='id_envoye_id',
        ),
    ]
