# Generated by Django 3.2.9 on 2022-04-12 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0034_remove_paiement_id_envoye_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id_envoye_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='quickstart.envoye'),
            preserve_default=False,
        ),
    ]
