# Generated by Django 3.2.9 on 2022-04-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0037_paiement_id_envoye_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id_envoye_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.envoye'),
        ),
    ]
