# Generated by Django 3.2.9 on 2022-04-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0044_alter_justifs_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justifs',
            name='id_envoye_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.envoye'),
        ),
    ]
