# Generated by Django 3.2.9 on 2022-04-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0047_bloque_config_blocage_config_rapport_rapport_rapport_droit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiches',
            fields=[
                ('id_fiches', models.AutoField(primary_key=True, serialize=False)),
                ('fiche_de_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_de_mission', to='quickstart.stepprocess')),
                ('id_process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.processus')),
                ('ordre_de_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_de_mission', to='quickstart.stepprocess')),
            ],
        ),
    ]
