# Generated by Django 3.2.9 on 2022-04-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0049_auto_20220425_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='step_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process1', to='quickstart.typesteps'),
        ),
    ]
