# Generated by Django 3.2.9 on 2022-04-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0050_alter_bloque_step_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='id_envoye_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='env', to='quickstart.envoye'),
        ),
    ]
