# Generated by Django 3.2.9 on 2022-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0051_rapport_id_envoye_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='id_envoye_id',
            new_name='id_envoye1',
        ),
    ]
