# Generated by Django 3.2.9 on 2022-04-29 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0052_rename_id_envoye_id_rapport_id_envoye1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='fichier',
            field=models.FileField(default=django.utils.timezone.now, upload_to='rapport'),
            preserve_default=False,
        ),
    ]
