# Generated by Django 3.2.9 on 2022-04-29 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0053_paiement_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='fichier',
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier',
            field=models.FileField(default=django.utils.timezone.now, upload_to='rapport'),
            preserve_default=False,
        ),
    ]
