# Generated by Django 3.2.9 on 2022-05-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0059_alter_config_rapport_validateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='rapport_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.config_rapport'),
        ),
    ]
